development:
  sessions:
    default:
      database: mongoid
      hosts:
        - 10.211.55.8:27017
test:
  sessions:
    default:
      database: mongoid_test
      hosts:
        - 10.211.55.8:27017